USE RBDHOTEL
GO
EXECUTE AS LOGIN = 'rbd_wlasciciel';
	EXECUTE dbo.UTWORZ_WIDOK_POKOJE 1; -- nie dzia³a WLASCICIEL nie ma uprawnien do schematu DBO
	SELECT * FROM wlasciciel.PERSONEL;
	SELECT * FROM [wlasciciel].[WYPOSAZENIE_POKOJOW_HOTELU];
	SELECT * FROM recepcja.POKOJE;
	EXEC wlasciciel.EDYTUJ_ZNIZKE 4, 20;
	EXEC wlasciciel.DODAJ_USLUGE 1, 'usluga test', 100;
	EXEC wlasciciel.USLUGA_ZMIEN_CENE 10, 999;
	EXEC wlasciciel.USLUGA_ZMIEN_NAZWE 10, 'UTest';
	EXEC wlasciciel.ZMIEN_CENE_POKOJU 2, 999;
	exec wlasciciel.ZMIEN_ILOSC_WYPOSAZENIA 1, 'KRZES£O', 4;
	EXEC wlasciciel.ZMIEN_LICZBE_OSOB_POKOJU 2, 4;
	EXEC wlasciciel.ZMIEN_NAZWE_HOTELU 3, 'HOT GD';
	EXEC wlasciciel.ZMIEN_NAZWE_WYPOSAZENIA 1, 'KRZES£O', 'KRZESLO';
	EXEC wlasciciel.ZMIEN_NUMER_POKOJU 2, 202;
	EXEC wlasciciel.ZMIEN_PENSJE 1, 999;
	EXEC wlasciciel.ZMIEN_STANOWISKO 1, 'POKOJOWKA';
REVERT;

select * from HOTEL..RBDHOTEL.ZNIZKI;
select * from HOTEL..RBDHOTEL.USLUGI WHERE ID_HOTELU = 1;
select * from HOTEL..RBDHOTEL.POKOJE;
select * from HOTEL..RBDHOTEL.WYPOSAZENIE;
select * from HOTEL..RBDHOTEL.HOTELE;
select * from HOTEL..RBDHOTEL.PERSONEL;

SELECT * 
FROM OPENROWSET(
    'OraOLEDB.Oracle', 
    'pd19';'rbdhotel';'12345', 
    'SELECT ID_HOTELU, 
            NR_POKOJU, 
            ID_REZERWACJI, 
            OPIS, 
            TO_CHAR(GODZINY_SPRZATANIA_POCZATEK, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINY_SPRZATANIA_POCZATEK, 
            TO_CHAR(GODZINY_SPRZATANIA_KONIEC, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINY_SPRZATANIA_KONIEC, 
            ID_PRACOWNIKA, 
            TO_CHAR(GODZINA_SPRZATANIA, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINA_SPRZATANIA 
     FROM RBDHOTEL.SPRZATANIE'
) AS OracleData;

SELECT * 
FROM OPENROWSET(
    'OraOLEDB.Oracle', 
    'pd19';'rbdhotel';'12345', 
    'SELECT ID_HOTELU, 
            NR_POKOJU, 
            ID_REZERWACJI, 
            OPIS, 
            TO_CHAR(GODZINY_NAPRAWIANIA_POCZATEK, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINY_SPRZATANIA_POCZATEK, 
            TO_CHAR(GODZINY_NAPRAWIANIA_KONIEC, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINY_SPRZATANIA_KONIEC, 
            ID_PRACOWNIKA, 
            TO_CHAR(GODZINA_NAPRAWY, ''YYYY-MM-DD HH24:MI:SS'') AS GODZINA_SPRZATANIA 
     FROM RBDHOTEL.NAPRAWY'
) AS OracleData;



EXECUTE AS LOGIN = 'rbd_recepcja';
	SELECT * FROM wlasciciel.PERSONEL; -- nie dzia³a RECEPCJA nie ma uprawnien do schematu WLASCICIEL
	SELECT * FROM recepcja.POKOJE;
	SELECT * FROM recepcja.KLIENCI;
	SELECT * FROM recepcja.WYPOSAZENIE_POKOJU(101); -- numer pokoju
	EXEC recepcja.OPLATA_ZNISZCZENIE 1, 0;
	EXEC recepcja.DODAJ_REZERWACJA_USULGA 1, 1, 1, 1;
	EXEC recepcja.POTWIERDZ_REZERWACJE 1, 1;
	EXEC recepcja.ZAKONCZ_REZERWACJE 1;
REVERT;
SELECT * FROM HOTEL..RBDHOTEL.REZERWACJE;
SELECT * FROM HOTEL..RBDHOTEL.REZERWACJE_USLUGI;

EXECUTE AS LOGIN = 'rbd_pokojowka';
	SELECT * FROM wlasciciel.PERSONEL; -- nie dzia³a POKOJOWKA nie ma uprawnien do schematu WLASCICIEL
	SELECT * FROM recepcja.POKOJE;	-- nie dzia³a POKOJOWKA nie ma uprawnien do schematu RECEPCJA
	EXEC pokojowka.POKOJ_POSPRZATANY 1, 1, 101, 1;
REVERT;
SELECT * FROM HOTEL..RBDHOTEL.SPRZATANIE;

EXECUTE AS LOGIN = 'rbd_konserwacja';
	SELECT * FROM wlasciciel.PERSONEL; -- nie dzia³a KONSERWACJA nie ma uprawnien do schematu WLASCICIEL
	SELECT * FROM recepcja.POKOJE;	-- nie dzia³a KONSERWACJA nie ma uprawnien do schematu RECEPCJA
REVERT;


EXECUTE AS LOGIN = 'rbd_klient';
	SELECT * FROM wlasciciel.PERSONEL; -- nie dzia³a KLIENT nie ma uprawnien do schematu WLASCICIEL
	SELECT * FROM recepcja.POKOJE;	-- nie dzia³a KLIENT nie ma uprawnien do schematu RECEPCJA

	-- Dodawanie klienta
	EXEC KLIENT.DODAJ_KLIENTA
		@IMIE = 'Nikodem',
		@NAZWISKO = 'Rutkowski',
		@EMAIL = 'nikodem.rutkowski@example.com',
		@NR_TELEFONU = '123456789',
		@ULICA = 'Kwiatów',
		@NR_DOMU = 10,
		@NR_MIESZKANIA = 5,
		@MIEJSCOWOSC = 'Warszawa',
		@KOD_POCZTOWY = '00-001',
		@KRAJ = 'Polska';

	EXEC KLIENT.DODAJ_REZERWACJE 1, 1, 2, '2024-07-11', '2024-07-12'; -- S¥ 2 POKOJE PASUJ¥CE
	EXEC KLIENT.USUN_REZERWACJE 2;
	EXEC KLIENT.DODAJ_GOSCIA 1, 'Janusz', 'Motyka';
	EXEC KLIENT.DODAJ_GOSCIA 1, 'TEST', 'TEST';
	EXEC KLIENT.USUN_GOSCIA 1, 'TEST', 'TEST';
	exec KLIENT.DO_POSPRZATANIA 1, 1, 101, 'opis', '10:00:00', '12:00:00';
	exec KLIENT.DO_NAPRAWY 1, 1, 101, 'opis', '10:00:00', '12:00:00';
REVERT;
SELECT * FROM HOTEL..RBDHOTEL.REZERWACJE;
SELECT * FROM HOTEL..RBDHOTEL.GOSCIE;
SELECT * FROM HOTEL..RBDHOTEL.SPRZATANIE;

select * from HOTEL..RBDHOTEL.HOTELE