-------------- -------------------------------- -------------- 
-------------- -- SPRAWDZENIE PROCEDUR SZEFA -- -------------- 
-------------- -------------------------------- -------------- 

EXEC SZEF.DODAJ_HOTEL('HOTEL_WARSZAWA', 'GdaÒska', 10, NULL, 'Warszawa', '00-001', 'Polska');

EXEC SZEF.ZMIEN_NAZWE_HOTELU(1, 'HOTEL_WAWA');
    
BEGIN
  SZEF.DODAJ_PRACOWNIKA(
    'Jan', 
    'Kowalski', 
    'jan.kowalski@example.com', 
    '123456789', 
    'Mickiewicza', 
    15, 
    3, 
    'Warszawa', 
    '00-001', 
    'Polska', 
    1, 
    3000, 
    'RECEPCJA'
  );
END;

EXEC SZEF.ZMIEN_PENSJE(1, 3500);
EXEC SZEF.ZMIEN_STANOWISKO(1, 'KONSERWATOR');
EXEC SZEF.ZWOLNIJ_PRACOWNIKA(1);

EXEC SZEF.DODAJ_POKOJ(1, 101, 2, 150);
EXEC SZEF.ZMIEN_LICZBE_OSOB_POKOJU(1, 4);
EXEC SZEF.ZMIEN_NUMER_POKOJU(1, 102);
EXEC SZEF.ZMIEN_CENE_POKOJU(1, 200);

EXEC SZEF.DODAJ_WYPOSAZENIE(1, '£Ûøko', 2);
EXEC SZEF.ZMIEN_ILOSC_WYPOSAZENIA(1, '£Ûøko', 4);
EXEC SZEF.ZMIEN_NAZWE_WYPOSAZENIA(1, '£Ûøko', 'Krzes≥o');

EXEC SZEF.DODAJ_USLUGE(1, 'SPA', 100);
EXEC SZEF.USLUGA_ZMIEN_CENE(1, 150);
EXEC SZEF.USLUGA_ZMIEN_NAZWE(1, 'MASAZ');

EXEC SZEF.DODAJ_ZNIZKE(0);
EXEC SZEF.EDYTUJ_ZNIZKE(1, 5);
EXEC SZEF.OBNIZ_ZNIZKI();

select * from hotele;
select * from adresy;
select * from personel;
select * from pokoje;
select * from wyposazenie;
select * from uslugi;
select * from znizki;
SELECT * FROM DANE_PERSONALNE;

-------------- ---------------------------------- -------------- 
-------------- -- SPRAWDZENIE PROCEDUR KLIENTA -- -------------- 
-------------- ---------------------------------- -------------- 

BEGIN
  KLIENT.DODAJ_KLIENTA(
    'Anna', 
    'Nowak', 
    'anna.nowak@example.com', 
    '987654321', 
    'Kwiatowa', 
    20, 
    1, 
    'KrakÛw', 
    '30-001', 
    'Polska'
  );
END;

EXEC KLIENT.DODAJ_REZERWACJE(1, 1, 2, TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-07-10', 'YYYY-MM-DD'));


select * from hotele;
select * from adresy;
select * from personel;
select * from pokoje;
select * from wyposazenie;
select * from uslugi;
select * from znizki;
SELECT * FROM DANE_PERSONALNE;
SELECT * FROM KLIENCI;


/*EXEC POKOJ_DO_NAPRAWYPOKOJ_DO_NAPRAWY(1, 123, 101, 'Uszkodzona klimatyzacja',
    TO_TIMESTAMP('2024-07-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    TO_TIMESTAMP('2024-07-01 17:00:00', 'YYYY-MM-DD HH24:MI:SS') 
);*/


----STARE-----

-------------- ------------ -------------- 
-------------- -- POKOJE -- -------------- 
-------------- ------------ --------------

------- HOTEL WARSZAWA
----------------------
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 101, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 102, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 103, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 104, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 105, 4, 600, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 201, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 202, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 203, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 204, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 205, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 206, 3, 450, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 301, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 302, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 303, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 304, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 305, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 306, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 307, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel Warszawa'), 308, 2, 300, 'TAK', 'NIE');

--------- HOTEL KRAK”W
----------------------
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 101, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 102, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 103, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 104, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 105, 4, 600, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 201, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 202, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 203, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 204, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 205, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 206, 3, 450, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 301, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 302, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 303, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 304, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 305, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 306, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 307, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel KrakÛw'), 308, 2, 300, 'TAK', 'NIE');

----------- HOTEL £”Dè
----------------------
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 101, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 102, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 103, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 104, 4, 600, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 105, 4, 600, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 201, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 202, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 203, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 204, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 205, 3, 450, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 206, 3, 450, 'TAK', 'NIE');

INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 301, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 302, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 303, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 304, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 305, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 306, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 307, 2, 300, 'TAK', 'NIE');
INSERT INTO POKOJE (ID_HOTELU, NR_POKOJU, LICZBA_OSOB, CENA, POSPRZATANY, WYMAGA_NAPRAWY)
VALUES ((SELECT ID_HOTELU FROM HOTELE WHERE NAZWA = 'Hotel £Ûdü'), 308, 2, 300, 'TAK', 'NIE');

--select * from pokoje;

-------------- ----------------- --------------
-------------- -- WYPOSAZENIE -- --------------
-------------- ----------------- --------------

-------------- -------------- -------------- 
-------------- -- PERSONEL -- -------------- 
-------------- -------------- -------------- 

INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Nowowiejska', 1, NULL, 'Warszawa', '00-002', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Marsza≥kowska', 5, NULL, 'Warszawa', '00-003', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Krucza', 7, NULL, 'Warszawa', '00-004', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Aleje Jerozolimskie', 12, NULL, 'Warszawa', '00-005', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Plac Zbawiciela', 3, NULL, 'Warszawa', '00-006', 'Polska');

INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('FloriaÒska', 8, NULL, 'KrakÛw', '31-001', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Grodzka', 10, NULL, 'KrakÛw', '31-002', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Szewska', 12, NULL, 'KrakÛw', '31-003', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('åwiÍtej Anny', 14, NULL, 'KrakÛw', '31-004', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Kanonicza', 16, NULL, 'KrakÛw', '31-005', 'Polska');

INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('D≥uga', 18, NULL, '£Ûdü', '80-001', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Mariacka', 20, NULL, '£Ûdü', '80-002', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('åw. Ducha', 22, NULL, '£Ûdü', '80-003', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Piwna', 24, NULL, '£Ûdü', '80-004', 'Polska');
INSERT INTO ADRESY (ULICA, NR_DOMU, NR_MIESZKANIA, MIEJSCOWOSC, KOD_POCZTOWY, KRAJ)
VALUES ('Chlebnicka', 26, NULL, '£Ûdü', '80-005', 'Polska');

----------------------------------------------------------------------------------------------

INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Jan', 'Kowalski', 'jan.kowalski@rbd.com', '123456789', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Nowowiejska' AND NR_DOMU = 1));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Anna', 'Nowak', 'anna.nowak@rbd.com', '234567890', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Marsza≥kowska' AND NR_DOMU = 5));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Piotr', 'ZieliÒski', 'piotr.zielinski@rbd.com', '345678901', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Krucza' AND NR_DOMU = 7));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Katarzyna', 'Wiúniewska', 'katarzyna.wisniewska@rbd.com', '456789012', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Aleje Jerozolimskie' AND NR_DOMU = 12));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Micha≥', 'WÛjcik', 'michal.wojcik@rbd.com', '567890123', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Plac Zbawiciela' AND NR_DOMU = 3));

INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Agnieszka', 'Lewandowska', 'agnieszka.lewandowska@rbd.com', '678901234', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'FloriaÒska' AND NR_DOMU = 8));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Tomasz', 'Dπbrowski', 'tomasz.dabrowski@rbd.com', '789012345', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Grodzka' AND NR_DOMU = 10));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Monika', 'KrÛl', 'monika.krol@rbd.com', '890123456', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Szewska' AND NR_DOMU = 12));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Krzysztof', 'Majewski', 'krzysztof.majewski@rbd.com', '901234567', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'åwiÍtej Anny' AND NR_DOMU = 14));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Joanna', 'KamiÒska', 'joanna.kaminska@rbd.com', '012345678', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Kanonicza' AND NR_DOMU = 16));

INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Pawe≥', 'Sikorski', 'pawel.sikorski@rbd.com', '123456780', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'D≥uga' AND NR_DOMU = 18));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Magdalena', 'Zawadzka', 'magdalena.zawadzka@rbd.com', '234567890', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Mariacka' AND NR_DOMU = 20));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Adam', 'Piotrowski', 'adam.piotrowski@rbd.com', '345678901', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'åw. Ducha' AND NR_DOMU = 22));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Ewa', 'Kowalczyk', 'ewa.kowalczyk@rbd.com', '456789012', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Piwna' AND NR_DOMU = 24));
INSERT INTO DANE_PERSONALNE (IMIE, NAZWISKO, EMAIL, NR_TELEFONU, ID_ADRESU)
VALUES ('Grzegorz', 'Witkowski', 'grzegorz.witkowski@rbd.com', '567890123', (SELECT ID_ADRESU FROM ADRESY WHERE ULICA = 'Chlebnicka' AND NR_DOMU = 26));

----------------------------------------------------------------------------------------------

INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'jan.kowalski@rbd.com'), 1, SYSDATE, 4000, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'anna.nowak@rbd.com'), 1, SYSDATE, 4500, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'piotr.zielinski@rbd.com'), 1, SYSDATE, 4200, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'katarzyna.wisniewska@rbd.com'), 1, SYSDATE, 4100, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'michal.wojcik@rbd.com'), 1, SYSDATE, 4300, 'Szef');

INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'agnieszka.lewandowska@rbd.com'), 2, SYSDATE, 4000, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'tomasz.dabrowski@rbd.com'), 2, SYSDATE, 4500, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'monika.krol@rbd.com'), 2, SYSDATE, 4200, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'krzysztof.majewski@rbd.com'), 2, SYSDATE, 4100, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'joanna.kaminska@rbd.com'), 2, SYSDATE, 4300, 'Szef');

INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'pawel.sikorski@rbd.com'), 3, SYSDATE, 4000, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'magdalena.zawadzka@rbd.com'), 3, SYSDATE, 4500, 'Recepcja');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'adam.piotrowski@rbd.com'), 3, SYSDATE, 4200, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'ewa.kowalczyk@rbd.com'), 3, SYSDATE, 4100, 'PokojÛwka');
INSERT INTO PERSONEL (ID_OSOBY, ID_HOTELU, DATA_ZATRUDNIENIA, PENSJA, STANOWISKO)
VALUES ((SELECT ID_OSOBY FROM DANE_PERSONALNE WHERE EMAIL = 'grzegorz.witkowski@rbd.com'), 3, SYSDATE, 4300, 'Szef');

----------------------------------------------------------------------------------------------


