-- Wszystkio co zawiea schemat dbo
------------------------------------
USE [RBDHOTEL]
GO
-------------- --------------------- -------------- 
-------------- -- PERSONEL HOTELU -- -------------- 
-------------- --------------------- -------------- 
CREATE OR ALTER PROCEDURE dbo.UTWORZ_WIDOK_PERSONEL_HOTELU
    @ID_HOTELU INT
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = '
        CREATE OR ALTER VIEW wlasciciel.PERSONEL_HOTELU AS
        SELECT * FROM HOTEL..RBDHOTEL.PERSONEL
        WHERE ID_HOTELU = ' + CAST(@ID_HOTELU AS NVARCHAR(10)) + ';
    ';

    EXEC sp_executesql @SQL;
END;
GO
-------------- ------------------- -------------- 
-------------- -- POKOJE HOTELU -- -------------- 
-------------- ------------------- -------------- 
CREATE OR ALTER PROCEDURE dbo.UTWORZ_WIDOK_POKOJE
    @ID_HOTELU INT
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = '
		CREATE OR ALTER VIEW recepcja.POKOJE AS
        SELECT h.Nazwa Hotel, p.Nr_pokoju Pokoj, p.liczba_osob [Liczba osob], p.Cena [Cena za dzien]
		FROM HOTEL..RBDHOTEL.POKOJE p
		JOIN  HOTEL..RBDHOTEL.HOTELE h ON p.ID_HOTELU = h.ID_HOTELU 
		WHERE p.ID_HOTELU = ' + CAST(@ID_HOTELU AS NVARCHAR(10)) + ';';
    EXEC sp_executesql @SQL;
END;
GO
-------------- ------------------------- -------------- 
-------------- -- WYPOSAZENIE POKOJOW -- -------------- 
-------------- ------------------------- -------------- 
CREATE OR ALTER PROCEDURE dbo.UTWORZ_WIDOK_WYPOSAZENIE_POKOJOW_HOTELU
    @ID_HOTELU INT
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = '
        CREATE OR ALTER VIEW wlasciciel.WYPOSAZENIE_POKOJOW_HOTELU AS
        SELECT p.NR_POKOJU, w.NAZWA, w.ILOSC FROM HOTEL..RBDHOTEL.WYPOSAZENIE w JOIN 
		HOTEL..RBDHOTEL.POKOJE p on w.ID_POKOJU = p.ID_POKOJU
        WHERE p.ID_HOTELU = ' + CAST(@ID_HOTELU AS NVARCHAR(10)) + ';
    ';

    EXEC sp_executesql @SQL;
END;
GO

CREATE VIEW recepcja.KLIENCI AS 
SELECT O.IMIE, O.NAZWISKO, O.EMAIL, O.NR_TELEFONU [NUMER TELEFONU], A.MIEJSCOWOSC, A.KOD_POCZTOWY [KOD POCZTOWY],
	A.ULICA, A.NR_DOMU [NUMER DOMU], A.NR_MIESZKANIA [NUMER MIESZKANIA], A.KRAJ
FROM HOTEL..RBDHOTEL.KLIENCI K
JOIN HOTEL..RBDHOTEL.DANE_PERSONALNE O ON K.ID_OSOBY=O.ID_OSOBY
JOIN HOTEL..RBDHOTEL.ADRESY A ON A.ID_ADRESU=O.ID_ADRESU;

CREATE OR ALTER VIEW wlasciciel.PERSONEL AS 
SELECT O.IMIE, O.NAZWISKO, O.EMAIL, O.NR_TELEFONU [NUMER TELEFONU], K.DATA_ZATRUDNIENIA [DATA ZATRUDNIENIA], K.PENSJA, K.STANOWISKO, A.MIEJSCOWOSC, A.KOD_POCZTOWY [KOD POCZTOWY],
	A.ULICA, A.NR_DOMU [NUMER DOMU], A.NR_MIESZKANIA [NUMER MIESZKANIA], A.KRAJ
FROM HOTEL..RBDHOTEL.PERSONEL K
JOIN HOTEL..RBDHOTEL.DANE_PERSONALNE O ON K.ID_OSOBY=O.ID_OSOBY
JOIN HOTEL..RBDHOTEL.ADRESY A ON A.ID_ADRESU=O.ID_ADRESU
WHERE K.DATA_ZWOLNIENIA IS NULL;


-------------- ------------------------------ -------------- 
-------------- -- TWORZENIE WIDOKOW HOTELU -- -------------- 
-------------- ------------------------------ -------------- 
DECLARE
	@ID_HOTELU INT = 1
BEGIN
	EXEC UTWORZ_WIDOK_PERSONEL_HOTELU @ID_HOTELU;
	EXEC UTWORZ_WIDOK_POKOJE_HOTELU @ID_HOTELU;
	EXEC UTWORZ_WIDOK_WYPOSAZENIE_POKOJOW_HOTELU @ID_HOTELU;
END;

SELECT * FROM [recepcja].[KLIENCI];
SELECT * FROM [recepcja].[POKOJE];
SELECT * FROM [wlasciciel].[PERSONEL_HOTELU];
SELECT * FROM [wlasciciel].[WYPOSAZENIE_POKOJOW_HOTELU];
