-- TWORZENIE BAZY
USE [MASTER]
GO
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'RBDHOTEL'
GO
use [master];
GO
USE [master]
GO
ALTER DATABASE [RBDHOTEL] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [RBDHOTEL]    Script Date: 17.06.2024 12:40:27 ******/
DROP DATABASE IF EXISTS [RBDHOTEL]
GO
CREATE DATABASE [RBDHOTEL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RBDHOTEL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RBDHOTEL.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RBDHOTEL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RBDHOTEL_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [RBDHOTEL] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [RBDHOTEL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RBDHOTEL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RBDHOTEL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RBDHOTEL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RBDHOTEL] SET ARITHABORT OFF 
GO
ALTER DATABASE [RBDHOTEL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RBDHOTEL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RBDHOTEL] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [RBDHOTEL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RBDHOTEL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RBDHOTEL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RBDHOTEL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RBDHOTEL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RBDHOTEL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RBDHOTEL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RBDHOTEL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RBDHOTEL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RBDHOTEL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RBDHOTEL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RBDHOTEL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RBDHOTEL] SET  READ_WRITE 
GO
ALTER DATABASE [RBDHOTEL] SET RECOVERY FULL 
GO
ALTER DATABASE [RBDHOTEL] SET  MULTI_USER 
GO
ALTER DATABASE [RBDHOTEL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RBDHOTEL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RBDHOTEL] SET DELAYED_DURABILITY = DISABLED 
GO
USE [RBDHOTEL]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [RBDHOTEL]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [RBDHOTEL] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
-- LOGINY I U¯YTKOWNICY
USE [master]
GO
DROP LOGIN [rbd_wlasciciel]
GO
CREATE LOGIN [rbd_wlasciciel] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
DROP LOGIN [rbd_recepcja]
GO
CREATE LOGIN [rbd_recepcja] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
DROP LOGIN [rbd_pokojowka]
GO
CREATE LOGIN [rbd_pokojowka]WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
DROP LOGIN [rbd_konserwacja]
GO
CREATE LOGIN [rbd_konserwacja] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [rbd_klient] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [RBDHOTEL]
GO
CREATE SCHEMA [wlasciciel] AUTHORIZATION [dbo]
GO
CREATE USER [wlasciciel] FOR LOGIN [rbd_wlasciciel] WITH DEFAULT_SCHEMA=[wlasciciel]
GO
CREATE SCHEMA [recepcja] AUTHORIZATION [dbo]
GO
CREATE USER [recepcja] FOR LOGIN [rbd_recepcja] WITH DEFAULT_SCHEMA=[recepcja]
GO
CREATE SCHEMA [pokojowka] AUTHORIZATION [dbo]
GO
CREATE USER [pokojowka] FOR LOGIN [rbd_pokojowka] WITH DEFAULT_SCHEMA=[pokojowka]
GO
CREATE SCHEMA [konserwacja] AUTHORIZATION [dbo]
GO
CREATE USER [konserwacja] FOR LOGIN [rbd_konserwacja] WITH DEFAULT_SCHEMA=[konserwacja]
GO
CREATE SCHEMA [klient] AUTHORIZATION [dbo]
GO
CREATE USER [klient] FOR LOGIN [rbd_klient] WITH DEFAULT_SCHEMA=[klient]
GO