USE [master]
GO
CREATE LOGIN [rbd_wlasciciel] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [rbd_recepcja] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [rbd_pokojowka]WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [rbd_konserwacja] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[RBDHOTEL], DEFAULT_LANGUAGE=[polski], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [RBDHOTEL]
GO
CREATE SCHEMA [wlasciciel] AUTHORIZATION [dbo]
GO
CREATE USER [wlasciciel] FOR LOGIN [rbd_wlasciciel] WITH DEFAULT_SCHEMA=[wlasciciel]
GO
CREATE SCHEMA [recepcja] AUTHORIZATION [dbo]
GO
CREATE USER [recepcja] FOR LOGIN [rbd_recepcja] WITH DEFAULT_SCHEMA=[recepcja]
GO
CREATE SCHEMA [pokojowka] AUTHORIZATION [dbo]
GO
CREATE USER [pokojowka] FOR LOGIN [rbd_pokojowka] WITH DEFAULT_SCHEMA=[pokojowka]
GO
CREATE SCHEMA [konserwacja] AUTHORIZATION [dbo]
GO
CREATE USER [konserwacja] FOR LOGIN [rbd_konserwacja] WITH DEFAULT_SCHEMA=[konserwacja]
GO
