GO
CREATE VIEW dbo.ADRESY AS
SELECT * FROM HOTEL..RBDHOTEL.ADRESY;
GO
CREATE VIEW dbo.DANE_PERSONALNE AS
SELECT * FROM HOTEL..RBDHOTEL.DANE_PERSONALNE;
GO
CREATE VIEW dbo.PERSONEL AS
SELECT * FROM HOTEL..RBDHOTEL.PERSONEL;
GO
CREATE VIEW dbo.KLIENCI AS
SELECT * FROM HOTEL..RBDHOTEL.KLIENCI;
GO
CREATE VIEW dbo.HOTELE AS
SELECT * FROM HOTEL..RBDHOTEL.HOTELE;
GO
CREATE VIEW dbo.POKOJE AS
SELECT * FROM HOTEL..RBDHOTEL.POKOJE;
GO
CREATE VIEW dbo.USLUGI AS
SELECT * FROM HOTEL..RBDHOTEL.USLUGI;
GO
CREATE VIEW dbo.REZERWACJE AS
SELECT * FROM HOTEL..RBDHOTEL.REZERWACJE;
GO
CREATE VIEW dbo.REZERWACJE_USLUGI AS
SELECT * FROM HOTEL..RBDHOTEL.REZERWACJE_USLUGI;
GO
CREATE VIEW dbo.GOSCIE AS
SELECT * FROM HOTEL..RBDHOTEL.GOSCIE;
GO
CREATE VIEW dbo.ZNIZKI AS
SELECT * FROM HOTEL..RBDHOTEL.ZNIZKI;
GO
CREATE VIEW dbo.WYPOSAZENIE AS
SELECT * FROM HOTEL..RBDHOTEL.WYPOSAZENIE;
GO
