-- W£AŒCICIEL
EXEC wlasciciel.ZWOLNIJ_PRACOWNIKA 5;
GO
EXEC wlasciciel.ZMIEN_STANOWISKO 3, 'POKOJÓWKA'; -- NIE DZIA£A
SELECT * FROM HOTEL..RBDHOTEL.PERSONEL;
GO
EXEC wlasciciel.ZMIEN_PENSJE 3, 9999;			 -- NIE DZIA£A
SELECT * FROM HOTEL..RBDHOTEL.PERSONEL;
GO
EXEC wlasciciel.ZMIEN_NUMER_POKOJU 1, 100;		 -- NIE DZIA£A
SELECT * FROM HOTEL..RBDHOTEL.POKOJE;
GO
EXEC wlasciciel.ZMIEN_ILOSC_WYPOSAZENIA 1, 'KRZES£O', 6;
SELECT * FROM HOTEL..RBDHOTEL.WYPOSAZENIE;
GO
EXEC wlasciciel.ZMIEN_NAZWE_WYPOSAZENIA 1, 'KRZES£O', 'K';
SELECT * FROM HOTEL..RBDHOTEL.WYPOSAZENIE;
GO
EXEC wlasciciel.USUN_WYPOSAZENIE 1, 'K';
SELECT * FROM HOTEL..RBDHOTEL.WYPOSAZENIE;
GO
EXEC wlasciciel.ZMIEN_NAZWE_HOTELU 1, 'HOTTTTTL';	-- NIE DZIA£A
SELECT * FROM HOTEL..RBDHOTEL.HOTELE;
GO
EXEC wlasciciel.ZMIEN_LICZBE_OSOB_POKOJU 1, 4;
SELECT * FROM HOTEL..RBDHOTEL.POKOJE;
GO
EXEC wlasciciel.ZMIEN_CENE_POKOJU 1, 9999;
SELECT * FROM HOTEL..RBDHOTEL.POKOJE;
GO
EXEC wlasciciel.USUN_ZNIZKE 3;
SELECT * FROM HOTEL..RBDHOTEL.ZNIZKI;
GO
EXEC wlasciciel.USLUGA_ZMIEN_CENE 3, 999;
SELECT * FROM HOTEL..RBDHOTEL.USLUGI;
GO
EXEC wlasciciel.USLUGA_ZMIEN_NAZWE 3, 'ZMIANA';
SELECT * FROM HOTEL..RBDHOTEL.USLUGI;
GO
EXEC wlasciciel.USUN_USLUGE 3;
SELECT * FROM HOTEL..RBDHOTEL.USLUGI;
GO
EXEC wlasciciel.USUN_POKOJ 2;
SELECT * FROM HOTEL..RBDHOTEL.POKOJE;
GO
EXEC wlasciciel.EDYTUJ_ZNIZKE 1, 1;
SELECT * FROM HOTEL..RBDHOTEL.ZNIZKI;